name: Version up Production Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
    # deploy:
    #     name: Deploy
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v2

    #         - uses: go-semantic-release/action@v1
    #           id: semrel
    #           with:
    #               github-token: ${{ secrets.GITHUB_TOKEN }}
    #               update-file: package.json
    #               dry: true
    #               force-bump-patch-version: true
    #               custom-arguments: '--no-ci'
    #               changelog-generator-opt: 'emojis=true'

    #         - uses: go-semantic-release/action@v1
    #           with:
    #               github-token: ${{ secrets.GITHUB_TOKEN }}
    #               update-file: package.json
    #               force-bump-patch-version: true
    #               custom-arguments: '--no-ci'
    #               changelog-generator-opt: 'emojis=true'

    #               name: Deploy Docker Build to GHCR
    image-push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set env
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.CR_PAT }}
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
              ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}